config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "theaters#index"
  
  resources :theaters do
    resources :movies
    resources :auditoria
  end

  resources :movies do
    resources :movie_screenings
  end

  resources :movie_screenings do
    resources :ticket_orders
  end
end

app/models/movie_screening.rb
class MovieScreening < ApplicationRecord
  belongs_to :movie
  belongs_to :theater
  has_many :ticket_orders, dependent: :destroy

  validates :movie_id, :theater_id, :screening_date, :start_time, presence: true
  validates :movie_id, :theater_id, numericality: { only_integer: true }

  scope :current_ordered_screenings, -> { where('screening_date >= ?', Date.today).order(:screening_date).order(:start_time)}

  def friendly_start_time
    start_time.strftime("%l:%M %p")
  end

  def friendly_screening_date
    screening_date.strftime("%b %e, %Y")
  end

  def tickets_sold
    ticket_orders.count
  end

  def tickets_remaining
    unsold_tickets = movie.auditorium.seating_capacity - tickets_sold
  end

  def sold_out?
    !(tickets_remaining > 0)
  end

  def disable_screening
    if sold_out?
      "disabled"
    end
  end

  def date_invalid_purchase?
    if screening_date < Date.today
      true
    else
      false
    end
  end
end

app/controllers/movie_screenings_controller.rb
class MovieScreeningsController < ApplicationController
  before_action :set_theater_and_movie
  before_action :set_movie_screening, only: [:show, :edit, :update, :destroy]
  
  def index
    @movie_screenings = @movie.movie_screenings.current_ordered_screenings
  end

  def new
    @movie_screening = MovieScreening.new
  end

  def create
    @movie_screening = MovieScreening.new(movie_screening_params)

    if @movie_screening.save
      flash[:success] = "New movie screening successfully added!"
      redirect_to movie_movie_screening_path(@movie, @movie_screening)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @movie_screening.update(movie_screening_params)
      flash[:success] = "Movie was successfully updated!"
      redirect_to movie_movie_screening_path(@movie, @movie_screening)
    else
      render :edit
    end
  end

  def destroy
    if @movie_screening.destroy
      flash[:success] = "Movie screening was successfully deleted!"
      redirect_to theater_path(@theater)
    else
      flash[:warning] = "Unable to delete the movie screening"
      redirect_to movie_movie_screening_path(@movie, @movie_screening)
    end
  end

  private

    def set_theater_and_movie
      @movie = Movie.find(params[:movie_id])
      @theater = @movie.theater
    end

    def set_movie_screening
      @movie_screening = MovieScreening.find(params[:id])
    end

    def movie_screening_params
      params.require(:movie_screening).permit(
        :movie_id,
        :theater_id,
        :screening_date,
        :start_time,
        :end_time
      )
    end
end

app/helpers/movie_screenings_helper.rb
module MovieScreeningsHelper
end

app/views/movie_screenings/_form.html.erb
<%= form_for([@movie, @movie_screening]) do |f| %>
  <% if @movie_screening.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie_screening.errors.count, "error") %> prohibited this movie screening from being saved:</h2>

      <ul>
      <% @movie_screening.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="well">
  
    <div class="form-group">
      <%= f.hidden_field :theater_id, value: @movie.theater.id, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.hidden_field :movie_id, value: @movie.id, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :screening_date %>
      <%= f.date_select :screening_date, { order: [:month, :day, :year] } %>
    </div>

    <div class="form-group">
      <%= f.label :start_time %>
      <%= f.time_select :start_time, { :ampm => true, :include_blank => true } %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-default" %>
    <% if @movie_screening.id %>
      <%= link_to 'Back To Screening', movie_movie_screening_path(@movie, @movie_screening), class: "btn btn-default" %>
    <% end %>
    <%= link_to 'Back To Movie', theater_movie_path(@theater, @movie), class: "btn btn-default" %>
  </div>
  <br>
<% end %>

app/views/movie_screenings/edit.html.erb
<div class="thumbnail padding-20">
  <h1>Edit Movie Screening For: <%= @movie.title %></h1>
  
  <div class="divider-20"></div>

  <%= render 'form' %>
</div>

app/views/movie_screenings/index.html.erb
<div class="thumbnail padding-20">
  <h1>Movie Screenings For: <%= @movie.title %></h1>
  
  <div class="divider-20"></div>
  
  <div class="well">
    <p>
      <strong>Theater:</strong>
      <%= @theater.name %>
    </p>

    <p>
      <strong>Auditorium:</strong>
      <%= @movie.auditorium.name %>
    </p>
  </div>
  <%= link_to 'Add Screening', new_movie_movie_screening_path(@movie), class: "btn btn-default" %>
</div>

<div class="thumbnail padding-20">
  <h3>Screenings</h3>

  <div class="divider-20"></div>
  
  <% if @movie_screenings.any? %>
    <% @movie_screenings.each do |movie_screening| %>
      <div class="well">
        <h3><%= link_to "#{movie_screening.friendly_screening_date} | #{movie_screening.friendly_start_time}", movie_movie_screening_path(@movie, movie_screening) %></h3>
        <p>
          <strong>Theater: </strong>
          <%= movie_screening.movie.theater.name %>
        </p>
        <p>
          <strong>Auditorium: </strong>
          <%= movie_screening.movie.auditorium.name %>
        </p>
        <% if movie_screening.sold_out? %>
          <h4 class="sold-out"><strong>Sold Out!</strong></h4>
        <% else %>
          <%= link_to 'Buy Ticket', new_movie_screening_ticket_order_path(movie_screening), class: "btn btn-xs btn-default" %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <h4>No screenings scheduled at this moment</h4>
  <% end %>
</div>

app/views/movie_screenings/new.html.erb
<div class="thumbnail padding-20">
  <h1>New Movie Screening For: <%= @movie.title %></h1>
  
  <div class="divider-20"></div>

  <%= render 'form' %>
</div>

app/views/movie_screenings/show.html.erb
<div class="thumbnail padding-20">
  <h1>Screening For: <%= @movie_screening.movie.title %></h1>

  
  <% if @movie_screening.sold_out? %>
    <span class="sold-out"><h3>Sold Out!</h3></span>
  <% end %>

  <div class="divider-20"></div>
  <div class="well">
    <p>
      <strong>Theater:</strong>
      <%= @movie.theater.name %>
    </p>

    <p>
      <strong>Auditorium:</strong>
      <%= @movie_screening.movie.auditorium.name %>
    </p>

    <p>
      <strong>Date:</strong>
      <%= @movie_screening.friendly_screening_date %>
    </p>

    <p>
      <strong>Start Time:</strong>
      <%= @movie_screening.friendly_start_time %>
    </p>

    <p>
      <strong>Run Time:</strong>
      <%= @movie_screening.movie.run_time_hours %>
    </p>

    <p>
      <strong>Tickets Available:</strong>
      <%= @movie_screening.tickets_remaining %>
    </p>
  </div>
  
  <div class="button-list">
    <% unless @movie_screening.sold_out? || @movie_screening.date_invalid_purchase? %>
      <%= link_to 'Buy Ticket', new_movie_screening_ticket_order_path(@movie_screening), class: "btn btn-default" %>
    <% end %>
    <%= link_to 'Edit', edit_movie_movie_screening_path(@movie, @movie_screening), class: "btn btn-default" %>
    <%= link_to 'View Ticket Orders', movie_screening_ticket_orders_path(@movie_screening), class: "btn btn-default" %>
    <%= link_to 'Back To Movie', theater_movie_path(@theater, @movie), class: "btn btn-default" %>
    <%= link_to 'Delete', movie_movie_screening_path(@movie, @movie_screening), method: :delete, data: { confirm: "Are you sure you want to delete?" },class: "btn btn-default" %>
  </div>
</div>