config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "theaters#index"
  
  resources :theaters do
    resources :movies
    resources :auditoria
  end

  resources :movies do
    resources :movie_screenings
  end

  resources :movie_screenings do
    resources :ticket_orders
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_theater
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  
  def index
    @movies = @theater.movies
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      flash[:success] = "New movie successfully added!"
      redirect_to theater_movie_path(@theater, @movie)
    else
      render :new
    end
  end

  def show
    @movie_screenings = @movie.movie_screenings.current_ordered_screenings
  end

  def edit
  end

  def update
    if @movie.update(movie_params)
      flash[:success] = "Movie was successfully updated!"
      redirect_to theater_movie_path(@theater, @movie)
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy

    if @movie.destroy
      flash[:success] = "Movie was successfully deleted!"
      redirect_to theater_path(@theater)
    else
      flash[:warning] = "Unable to delete the movie"
      redirect_to theater_movie_path(@theater, @movie)
    end
  end

  private

    def set_theater
      @theater = Theater.find(params[:theater_id])
    end

    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(
        :auditorium_id,
        :theater_id,
        :title,
        :run_time_minutes,
        :ticket_price
      )
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for([@theater, @movie]) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.hidden_field :theater_id, value: @theater.id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :auditorium_id %>
    <%= f.collection_select(:auditorium_id, Auditorium.where(theater_id: @theater.id), :id, :name, :prompt => 'Select Auditorium', class: "form-control") %>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :run_time_minutes %>
    <%= f.number_field :run_time_minutes, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :ticket_price %>
    <%= f.number_field :ticket_price, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-default" %>

    <% if @movie.id %>
      <%= link_to 'Back To Movie', theater_movie_path(@theater, @movie), class: "btn btn-default" %>
    <% end %>
  </div>
  <br>
<% end %>

app/views/movies/edit.html.erb
<div class="thumbnail padding-20">
  <h1>Edit Movie</h1>
  
  <div class="divider-20"></div>
  
  <%= render 'form' %>
</div>

app/views/movies/index.html.erb
<div class="thumbnail padding-20">
  <h1>Movies at <%= @theater.name %></h1>

  <div class="divider-20"></div>

  <%= link_to 'Add Movie', new_theater_movie_path(@theater), class: "btn btn-default" %>

  <div class="divider-20"></div>

  <% if @movies.any? %>
    <% @movies.each do |movie| %>
      <div class="well">
        <h3><%= link_to movie.title, theater_movie_path(@theater, movie) %></h3>
        <p>
          <strong>Auditorium: </strong>
          <%= movie.auditorium.name %>
        </p>
        <% movie.movie_screenings.current_ordered_screenings.each do |movie_screening| %>
          <%= link_to "#{movie_screening.friendly_screening_date} | #{movie_screening.friendly_start_time}", movie_movie_screening_path(movie, movie_screening), class: "btn btn-sm btn-primary #{movie_screening.disable_screening}" %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <h4>No movies for <%= @theater.name %> at this moment</h4>
  <% end %>
</div>

app/views/movies/new.html.erb
<div class="thumbnail padding-20">
  <h1>New Movie</h1>
  
  <div class="divider-20"></div>
  
  <%= render 'form' %>
</div>

app/views/movies/show.html.erb
<div class="thumbnail padding-20">
  <h1><%= @movie.title %></h1>

  <div class="divider-20"></div>
  
  <div class="well">
    <p>
      <strong>Theater:</strong>
      <%= @theater.name %>
    </p>

    <p>
      <strong>Auditorium:</strong>
      <%= @movie.auditorium.name %>
    </p>

    <p>
      <strong>Run Time:</strong>
      <%= @movie.run_time_hours %>
    </p>

    <p>
      <strong>Ticket Price:</strong>
      <%= number_to_currency(@movie.ticket_price) %>
    </p>
  </div>
    
  <div class="button-list">
    <%= link_to 'Edit', edit_theater_movie_path(@theater, @movie), class: "btn btn-default" %>
    <%= link_to 'Back To Theater', theater_path(@theater), class: "btn btn-default" %>
    <%= link_to 'Add Screening', new_movie_movie_screening_path(@movie), class: "btn btn-default" %>
    <%= link_to 'Delete', theater_movie_path(@theater, @movie), method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: "btn btn-default" %>
  </div>
</div>
  

<div class="thumbnail padding-20">
  <h3>Screenings</h3>

  <div class="divider-20"></div>

  <% if @movie_screenings.any? %>
    <% @movie_screenings.each do |movie_screening| %>
      <div class="well">
        <h3><%= link_to "#{movie_screening.friendly_screening_date} | #{movie_screening.friendly_start_time}", movie_movie_screening_path(@movie, movie_screening), class: "disable" %></h3>
        <p>
          <strong>Theater: </strong>
          <%= movie_screening.movie.theater.name %>
        </p>
        <p>
          <strong>Auditorium: </strong>
          <%= movie_screening.movie.auditorium.name %>
        </p>
        <% if movie_screening.sold_out? %>
          <h4 class="sold-out"><strong>Sold Out!</strong></h4>
        <% else %>
          <%= link_to 'Buy Ticket', new_movie_screening_ticket_order_path(movie_screening), class: "btn btn-xs btn-default" %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <h4>No screenings scheduled at the moment</h4>
  <% end %>
</div>