config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "theaters#index"
  
  resources :theaters do
    resources :movies
    resources :auditoria
  end

  resources :movies do
    resources :movie_screenings
  end

  resources :movie_screenings do
    resources :ticket_orders
  end
end

app/models/theater.rb
class Theater < ApplicationRecord
  has_many :auditoria, dependent: :destroy
  has_many :movies, dependent: :destroy
  has_many :movie_screenings, dependent: :destroy
  has_many :ticket_orders, through: :movie_screenings, dependent: :destroy
  
  validates :name, :manager, :street_address, :city, :state, :zip, presence: true

  def full_address
    "#{street_address} \n#{city}, #{state} #{zip}"
  end
end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  before_action :set_theater, only: [:show, :edit, :update, :destroy]
  
  def index
    @theaters = Theater.all
  end

  def new
    @theater = Theater.new
  end

  def create
    @theater = Theater.new(theater_params)

    if @theater.save
      flash[:success] = "New theater successfully created!"
      redirect_to theater_path(@theater)
    else
      render :new
    end
  end

  def show
    @auditoriums = @theater.auditoria
    @movies = @theater.movies
    @ticket_orders = @theater.ticket_orders.order_date_asc
  end

  def edit
  end

  def update
    if @theater.update(theater_params)
      flash[:success] = "Theater was successfully updated!"
      redirect_to theater_path(@theater)
    else
      render :edit
    end
  end

  def destroy
    if @theater.destroy
      flash[:success] = "Theater was successfully deleted!"
      redirect_to theaters_path
    else
      flash[:warning] = "Unable to delete the theater"
      redirect_to theater_path(@theater)
    end
  end

  private

    def set_theater
      @theater = Theater.find(params[:id])
    end

    def theater_params
      params.require(:theater).permit(
        :name,
        :manager,
        :street_address,
        :city,
        :state,
        :zip
      )
    end
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/views/theaters/_form.html.erb
<%= form_for(@theater) do |f| %>
  <% if @theater.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theater.errors.count, "error") %> prohibited this theater from being saved:</h2>

      <ul>
      <% @theater.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :manager %>
    <%= f.text_field :manager, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :street_address %>
    <%= f.text_field :street_address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.select(:state, options_for_select(us_states, @theater.state), :prompt => "Select State", class: "form-control" ) %>
  </div>

  <div class="form-group">
    <%= f.label :zip %>
    <%= f.text_field :zip, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-default" %>
    <% if @theater.id %>
      <%= link_to 'View Theater', theater_path(@theater), class: "btn btn-default" %>
    <% end %>
    <%= link_to 'Back To Theaters', theaters_path, class: "btn btn-default" %>
  </div>
  <br>
<% end %>

app/views/theaters/edit.html.erb
<div class="thumbnail padding-20">
  <h1>Edit Theater</h1>
  
  <div class="divider-20"></div>
  
  <%= render 'form' %>
</div>

app/views/theaters/index.html.erb
<div class="thumbnail padding-20">
  <h1>Movie Theaters</h1>

  <div class="divider-20"></div>

  <% if @theaters.any? %>
    <% @theaters.each do |theater| %>
      <div class="well">
        <h3><%= link_to theater.name, theater_path(theater) %></h3>
        <p class="pre-line"><%= theater.full_address %></p>
      </div>
    <% end %>
  <% else %>
    <h4>No theaters at the moment</h4>
  <% end %>
</div>

app/views/theaters/new.html.erb
<div class="thumbnail padding-20">
  <h1>New Theater</h1>
  
  <div class="divider-20"></div>

  <%= render 'form' %>
</div>

app/views/theaters/show.html.erb
<div class="thumbnail padding-20">
  <h1><%= @theater.name %></h1>
  
  <div class="divider-20"></div>

  <div class="well">
    <p>
      <strong>Manager:</strong>
      <%= @theater.manager %>
    </p>

    <p>
      <strong>Street Address:</strong>
      <%= @theater.full_address %>
    </p>
  </div>
  
  <div class="button-list">
    <%= link_to 'Edit', edit_theater_path(@theater), class: "btn btn-default" %>
    <%= link_to 'Add Movie', new_theater_movie_path(@theater), class: "btn btn-default" %>
    <%= link_to 'Add Auditorium', new_theater_auditorium_path(@theater), class: "btn btn-default" %>
    <%= link_to 'Back To Theaters', theaters_path, class: "btn btn-default" %>
    <%= link_to 'Delete', theater_path(@theater), method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: "btn btn-default" %>
  </div>
</div>

<div class="bootstrap-tabs">
  <!-- Nav tabs -->
  <ul class="nav nav-pills" role="tablist">
    <li role="presentation" class="active"><a href="#movies" aria-controls="movies" role="tab" data-toggle="tab">Movies</a></li>
    <li role="presentation"><a href="#auditoriums" aria-controls="auditoriums" role="tab" data-toggle="tab">Auditoriums</a></li>
    <li role="presentation"><a href="#ticket-orders" aria-controls="ticket-orders" role="tab" data-toggle="tab">Orders</a></li>
    <li role="presentation"><a href="#movie-ticket-orders" aria-controls="movie-ticket-orders" role="tab" data-toggle="tab">Orders By Movie</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="movies">
      <% if @movies.any? %>
        <% @movies.each do |movie| %>
          <div class="well">
            <h3><%= link_to movie.title, theater_movie_path(@theater, movie) %></h3>
            <p>
              <strong>Auditorium: </strong>
              <%= movie.auditorium.name %>
            </p>
            <% movie.movie_screenings.current_ordered_screenings.each do |movie_screening| %>
              <%= link_to "#{movie_screening.friendly_screening_date} | #{movie_screening.friendly_start_time}", movie_movie_screening_path(movie, movie_screening), class: "btn btn-sm btn-primary #{movie_screening.disable_screening}" %>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <h4>No Movies</h4>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane" id="auditoriums">
      <% if @auditoriums.any? %>
        <% @auditoriums.each do |auditorium| %>
          <div class="well">
            <h3><%= link_to auditorium.name, theater_auditorium_path(@theater, auditorium) %></h3>
          </div>
        <% end %>
      <% else %>
        <h4>No Auditoriums</h4>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane" id="ticket-orders">
      <div class="thumbnail padding-20">
        <h4>
          <strong>Total Orders: </strong>
          <%= @ticket_orders.count %>
          </h4>
      </div>
      <% @ticket_orders.each do |ticket_order| %>
        <div class="well">
          <%= render 'ticket_orders/ticket_order_info', ticket_order: ticket_order %>
        </div>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane" id="movie-ticket-orders">
      <% if @movies.any? %>
        <% @movies.order_by_tickets_sold.each do |movie| %>
          <div class="well">
            <h3><%= link_to movie.title, theater_movie_path(@theater, movie) %></h3>
            <p>
              <strong>Total Orders: </strong>
              <%= movie.total_orders %>
            </p>
            <% if movie.ticket_orders.any? %>
              <button class="btn btn-xs btn-default view-orders-btn">View Orders</button>
              <div class="divider-10"></div>

              <div class="orders-for-movie hide-element">
                <% movie.ticket_orders.order_date_desc.each do |ticket_order| %>
                  <div class="thumbnail padding-20">
                    <%= render 'ticket_orders/ticket_order_info', ticket_order: ticket_order %>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <h4>No movie ticket orders</h4>
      <% end %>
    </div>
  </div>
</div>