config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "theaters#index"
  
  resources :theaters do
    resources :movies
    resources :auditoria
  end

  resources :movies do
    resources :movie_screenings
  end

  resources :movie_screenings do
    resources :ticket_orders
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Theater App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Movie Theaters</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% if @theater && @theater.id %>
              <li class="active"><%= link_to "Theater Home", theater_path(@theater) %></li>
            <% end %>
            <% if @theater && @theater.id %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Manage Theater <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "View Auditoriums", theater_auditoria_path(@theater) %></li>
                  <li><%= link_to "View Movies", theater_movies_path(@theater) %></li>
                  <li><%= link_to "Add Auditorium", new_theater_auditorium_path(@theater) %></li>
                  <li><%= link_to "Add Movie", new_theater_movie_path(@theater) %></li>
                </ul>
              </li>
            <% end %>
            <li><%= link_to "Add Theater", new_theater_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container">
      <% flash.each do |name, message| %>
        <div class="alert alert-<%= name == "alert" || name == "notice" ? "warning" : name %> alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <strong><%= message %></strong>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>